apiVersion: v1
kind: ConfigMap
metadata:
  name: boundary-controller-config
  namespace: {{ include "boundary.namespace" . }}
  labels:
    app.kubernetes.io/name: boundary-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  boundary-controller-config.hcl: |
    {{- .Values.controller.config | nindent 4 }}
