{{- if .Values.controller.ingress.enabled -}}
{{- $extraPaths := .Values.controller.ingress.extraPaths -}}
{{- $serviceName := "boundary-controller" -}}
{{- $servicePort := 9200 -}}
{{- $pathType := .Values.controller.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "boundary.fullname" . }}-controller
  namespace: {{ include "boundary.namespace" . }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: boundary-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.controller.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.controller.ingress.annotations }}
  annotations:
    {{- toYaml .Values.controller.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.controller.ingress.tls }}
  tls:
  {{- range .Values.controller.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- if .Values.controller.ingress.ingressClassName }}
  ingressClassName: {{ .Values.controller.ingress.ingressClassName }}
{{- end }}
  rules:
  {{- range .Values.controller.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{ if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
        {{- range (.paths | default (list "/")) }}
          - path: {{ . }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
        {{- end }}
  {{- end }}
{{- end }}
