{{- if .Values.initialize.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: boundary-init-config
  namespace: {{ include "boundary.namespace" . }}
  labels:
    app.kubernetes.io/name: boundary-init
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  boundary-controller-config.hcl: |
    {{- .Values.controller.config | nindent 4 }}
{{- end}}
