apiVersion: v1
kind: ConfigMap
metadata:
  name: boundary-worker-config
  namespace: {{ include "boundary.namespace" . }}
  labels:
    app.kubernetes.io/name: boundary-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  boundary-worker-config.hcl: |
    {{- .Values.worker.config | nindent 4 }}
